name: Build Ionic APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Ionic and Cordova
        run: |
          npm install -g @ionic/cli cordova

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cap add android

      - name: Build the app
        run: ionic build

      - name: Copy web assets
        run: ionic cap copy android

      - name: Build APK with Gradle
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MapaApp-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
