name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Ionic CLI
        run: npm install -g @ionic/cli

      - name: Install project dependencies
        run: npm install

      - name: Add Android platform if not present
        run: |
          if [ ! -d "android" ]; then
            ionic cap add android
          else
            echo "Android platform already added."
          fi

      - name: Build the app
        run: ionic build

      - name: Copy Web Assets
        run: npx cap copy android

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MapaApp-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
